alias ls='ls -GFt'

# Git
alias gs='git status'
alias ga='git add'
alias gd='git diff'
alias gc='git commit'
alias ggraph='git log --all --decorate --oneline --graph'
alias tag-list='git tag --list --sort=v:refname | tail -5'
alias git-amend-no-edit='git commit -a --amend --no-edit'

# vim
alias vi='echo -en "\e]0; $(basename $(pwd)) \a"; nvim'
alias vim='echo -en "\e]0; $(basename $(pwd)) \a"; nvim'

alias title='echo -en "\e]0; $(basename $(pwd)) \a"'
alias sign-file='ssh-keygen -Y sign -f ~/.ssh/id_rsa -n file'

# Docker
alias d="docker"
alias docker-vm='docker run -it --rm --privileged --pid=host justincormack/nsenter1'
alias docker-desktop='open docker-desktop://dashboard/open'
alias docker-pty='socat -d -d ~/Library/Containers/com.docker.docker/Data/debug-shell.sock pty,rawer'
alias dive='docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_API_VERSION=1.37 wagoodman/dive:latest'
alias docker-lsp-ps='docker run --rm -v /var/run/docker.sock:/var/run/docker.sock vonwig/lsp-ls'
alias docker-mcp-registry='docker run --rm -v docker-prompts:/prompts busybox /bin/sh -c "cat /prompts/registry.yaml"'
alias docker-mcp-log='docker run --name docker_mcp_log --rm -t --init -v docker-prompts:/prompts alpine:latest tail -f /prompts/log/docker-mcp-server.out'
alias docker-ps-hidden='docker ps -f LABEL=com.docker.desktop.service=true'
alias mcp-inspector='npx @modelcontextprotocol/inspector@latest'
alias goose-session='goose session --with-remote-extension'
alias op-signin='op signin --account my.1password.com'
alias env-anthropic='export ANTHROPIC_API_KEY=$(op read op://Personal/bwvhyey4plej6yuhy6fprkwpwa/value)'
alias env-openai='export OPENAI_API_KEY=$(op read op://Personal/dxl5k576lpqb52h2ilzzohtmye/value)'
alias lv='/Users/slim/slimslenderslacks/logviewer/logviewer /Users/slim/.docker/mcp/logs'

function docker-registry {
  docker run --rm -v docker-prompts:/prompts busybox /bin/sh -c "echo '$1' > /prompts/registry.yaml"
}

# How do you call a bash function
# How do you pop args in a bash function
# In bash how does shift work
function prompts {
    host_dir=$1
    prompts_dir=$2
    shift 2
    echo "host_dir: $host_dir"
    echo "prompts_dir: $prompts_dir"
    echo "extra_args: $@"
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
	       --mount type=volume,source=docker-prompts,target=/prompts \
	       --mount type=bind,source=/Users/slim/docker/labs-ai-tools-for-devs,target=/app/local \
               --mount type=bind,source=$HOME/.openai-api-key,target=/root/.openai-api-key \
	       --workdir /app \
	       vonwig/prompts:latest \
	         run --user jimclark106 \
		     --platform "$(uname -o)" \
		     --host-dir "$host_dir" \
		     --prompts-dir "local/$prompts_dir" \
                     "$@"
}

function verify-file {
    ssh-keygen -Y verify -f ~/.ssh/allowed_signers -I $1 -n file -s $2 < $3
}

function daws-creds {
  export AWS_PROFILE=SupplyChainEngineers-111664719423
  aws sts get-caller-identity > /dev/null || aws sso login &&
  aws sts get-caller-identity > /dev/null &&
  JSON_BASEPATH="${HOME}/.aws/cli/cache"
  json_file=$(ls -tr "${JSON_BASEPATH}" | tail -n1)
  export AWS_ACCESS_KEY_ID=$(cat ${JSON_BASEPATH}/${json_file} | jq -r '.Credentials.AccessKeyId')
  export AWS_SECRET_ACCESS_KEY=$(cat ${JSON_BASEPATH}/${json_file} | jq -r '.Credentials.SecretAccessKey')
  export AWS_SESSION_TOKEN=$(cat ${JSON_BASEPATH}/${json_file} | jq -r '.Credentials.SessionToken')
  echo "Exported AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN"
}

export PATH=~/docker/mcp-gateway/dist:~/docker/cagent/bin:~/.local/bin/:/opt/homebrew/bin:$PATH

export IN_REPL=true
export AWS_IAM_USER=jim
export ATOMIST_ROOT=~/atomist
export BB_SCRIPTS=/Users/slim/atmhq/bb_scripts
export BB_LOCAL=TRUE
export JWT_CREATOR="/Users/slim/atmhq/jwt-creator"
export GPG_TTY=$(tty)

export NIXNAME=macbook-pro-m1
